# Generated by Django 2.2 on 2021-03-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxiservice',
            old_name='DOLocationID',
            new_name='do_location_id',
        ),
        migrations.RenameField(
            model_name='taxiservice',
            old_name='PULocationID',
            new_name='pu_location_id',
        ),
        migrations.RenameField(
            model_name='taxiservice',
            old_name='ratecodeID',
            new_name='rate_code_id',
        ),
        migrations.RenameField(
            model_name='taxiservice',
            old_name='vendorID',
            new_name='vendor_id',
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='congestion_surcharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='extra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='fare_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='improvement_surcharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='mta_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='store_and_fwd_flag',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='tip_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='tolls_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='trip_distance',
            field=models.FloatField(),
        ),
    ]
