# Generated by Django 2.2 on 2021-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxiservice',
            old_name='ratecodeID',
            new_name='RatecodeID',
        ),
        migrations.RenameField(
            model_name='taxiservice',
            old_name='vendorID',
            new_name='VendorID',
        ),
    ]
