# Generated by Django 2.2 on 2021-03-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210302_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiservice',
            name='congestion_surcharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='extra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='fare_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='improvement_surcharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='mta_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='tip_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='tolls_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxiservice',
            name='trip_distance',
            field=models.FloatField(),
        ),
    ]
